### ISSUE TITLE
Is the results of this method higher than AHDRNet?

### ISSUE THREAD

**Issue by LiuzhuForFun** [Galaxies99/NHDRRNet-pytorch#1]
Thanks a lots for your contribution. I look forward to obtain a baseline based on Pytorch. But I cannot re-implement the original results. I want to ask one question: is the results of this method higher than AHDRNet?

**Comment by Galaxies99** [comment]
Hello!

According to the original papers (table 3 of AHDRNet paper and table 1 of NHDRRNet paper), the numerical results shown that this method is NOT higher than AHDRNet (for example, HDR-VDP-2 metrics, AHDRNet 62.3 v.s. NHDRRNet 61.2).

You may use this method as an alternative, but according to my training experience, the network is also not easy to reach convergence. The original authors did not releases all detailed parameters they used for training, so it may need more parameter-adjustments to improve the performance. After training 3 days on 4x RTX TITAN, I also found that the results is not so good as the original results stated in the paper.

Some advice: AHDRNet has an official repository (see [https://github.com/qingsenyangit/AHDRNet](https://github.com/qingsenyangit/AHDRNet)), you may refer to the PyTorch implementation there for better results. You can use the trained models in that repository for inference if you just want to use that method as a baseline. It may help to re-implement the original results.

**Comment by LiuzhuForFun** [comment]
Thanks a lot. The official repository of AHDRNet also lack some basic training details and manuscripts.
