### ISSUE TITLE
Further speedup can be obtained by processing LDR2HDR on GPU

### ISSUE THREAD

**Issue by dongdong4fei** [Galaxies99/NHDRRNet-pytorch#2]
Hello, thank you for your sharing the code！

As i profiled your training code， i found that about 40% of the time were cost by the function LDR2HDR, which could be saved by doing this process on GPU in parallel.
A friendly tip~

**Comment by Galaxies99** [comment]
Hello! Thank you for your suggestions!

I agree with you that it can be optimized. It will be fixed in a few days since I'm a little busy right now. Also, a PR is always welcomed if convenient!

Thank you again for your kindly advice!
