### ISSUE TITLE
Would you share your pretrained model?

### ISSUE THREAD

**Issue by UdonDa** [Galaxies99/NHDRRNet-pytorch#4]
Hi, @Galaxies99!

I train your model and validate the qualitative score.
However, I can not reproduce your results reported in the pepar.

So, would you share your pre-trained models?

Best,

**Comment by Galaxies99** [comment]
Hi!

First, I'm not the author the NHDRRNet paper, here is my re-implementation according to the paper.
Also, during my own experiments, I can not reproduce results reported in the paper, either.
Unfortunately, my own checkpoints are lost during a server down. But I guess the results is similar with yours, that is, far from which is reported in the paper.

Sorry that I cannot help you. I suggest that you may contact the original authors of the paper and ask them for the models and source codes for better performances.
